services:
  - type: web
    name: tradingview-ta-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: "10000"   # Render provides its own PORT in runtime; this is optional/default
